# Generated by Django 4.1.3 on 2022-12-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='client/')),
            ],
        ),
    ]
